BEGIN TRANSACTION;

DROP TABLE IF EXISTS "KanSe";

DROP TABLE IF EXISTS "harOppgave";

DROP TABLE IF EXISTS "oppgave";

DROP TABLE IF EXISTS "spillerRolle";

DROP TABLE IF EXISTS "erIAkt";

DROP TABLE iF EXISTS "rolle";

DROP TABLE IF EXISTS "akt";

DROP TABLE IF EXISTS "skuespiller";

DROP TABLE IF EXISTS "ansatt";

DROP TABLE IF EXISTS "billett";

DROP TABLE IF EXISTS "billettKjøp";

DROP TaBLE IF EXISTs "forestilling";

DROP TABLE IF EXISTS "kundeProfil";

DROP TABLE IF EXISTS "kundeGruppe";

DROP TABLE IF EXISTS "plass";

DROP TABLE IF EXISTS "teaterStykke";

DROP TABLE IF EXISTS "sal";

COMMIT;
